### ISSUE TITLE
[PROJ] Improve favicon, screenshots

### ISSUE THREAD

**Issue by updownupdown** [vapurrmaid/bpm#44]

**Comment by vapurrmaid** [comment]
Definitely!

We can grab PNGs from final design of #43

**Comment by vapurrmaid** [comment]
- [ ] README.md screenshot
- [ ] favicon.ico
- [ ] 192, 512 PWA manifest PNGs
- [ ] remove 192, 512 JPGs
- [ ] social preview (likely requires cropped view)
